### ISSUE TITLE
News App

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Flutter#15]
# Create a News App in Flutter.
Any number of people can work on a single issue,
This issue is open to all.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by 1-Sanchit-1** [comment]
i work on this can you please assign me

**Comment by Raghavvvvv** [comment]
Hello, I am Raghav Jha.
I want to work on this issue.
Will you assign me to work on this?

**Comment by G1Joshi** [comment]
This Issue is open to all and we want as much quantity PR as our Community can build.
**Happy C0D1NG** 🚀

**Comment by soam1** [comment]
@G1Joshi how about this one? should I add this one bro? [news app](https://github.com/soam1/Mukhya-Samachar)
