### ISSUE TITLE
Todo App

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Flutter#3]
# Create a Todo App in Flutter.
Any number of people can work on a single issue,
This issue is open to all.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by Adiii1436** [comment]
Hello I want to work on this issue!

**Comment by G1Joshi** [comment]
This Issue is open to all and we want as much quantity PR as our Community can build.
**Happy C0D1NG** 🚀

**Comment by ekakshjanweja** [comment]
Hi can I work on this issue @G1Joshi

**Comment by PrajwalGKale** [comment]
## Greetings , **`@G1Joshi `** 
> **I was looking for a repository to contribute to open source and found this one.**
**Can you assign this issue to me? I'm familiar with the _Flutter Framework_ . And I would love to do it.**

_-Regards, thanks._ 👾

**Comment by 0kt1** [comment]
Hello @G1Joshi  , I'm eager to contribute. Please assign me.
