### ISSUE TITLE
Calculator App

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Flutter#4]
# Create a Calculator App in Flutter.
Any number of people can work on a single issue,
This issue is open to all.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by mohith2883** [comment]
Hey @G1Joshi  a basic calculator is enough ?

**Comment by Sriver27** [comment]
Can you please assign it to me?

**Comment by Sriver27** [comment]
@G1Joshi

**Comment by G1Joshi** [comment]
This Issue is open to all and we want as much quantity PR as our Community can build.
**Happy C0D1NG** 🚀

**Comment by RitwikSingh28** [comment]
@G1Joshi May I add a Complex Calculator App, whose sole task would be to perform arithmetic operations among two complex numbers (addition, subtraction, multiplication, division and modulus). Attaching the screenshot below.

![ComplexCalc](https://user-images.githubusercontent.com/106133014/197396702-49076a12-3b95-4efa-a279-3731ec0b935b.jpeg)
