### ISSUE TITLE
BMI Calculator

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Flutter#6]
# Create a BMI Calculator App in Flutter.
Any number of people can work on a single issue,
This issue is open to all.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by apoorva1823000** [comment]
Hi I would like to contribute over this project

**Comment by Sriver27** [comment]
Can you please assign it to me? @G1Joshi . I am willing to contribute towards flutter community,

**Comment by Adiii1436** [comment]
Hello I want to work on this issue. I will create a simplistic bmi calculator using flutter.

**Comment by areeba-farooq** [comment]
I would love to contribute to this issue. can you please assign this to me?

**Comment by charchit957** [comment]
Can you please assign this to me? I would love to contribute towards flutter community.

**Comment by G1Joshi** [comment]
This Issue is open to all and we want as much quantity PR as our Community can build.
**Happy C0D1NG** 🚀

**Comment by Utpal02** [comment]
I would love to contribute to this issue, may you pls assign it to me.

**Comment by PrajwalGKale** [comment]
## Greetings, **@gdsc-mitadt**
>**I was looking for a repository to contribute to open source and found this one.**
**Can you assign this to me? I'm familiar with the *Flutter framework* .**
