### ISSUE TITLE
Tic Tac Toe Game

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Flutter#7]
# Create a Tic Tac Toe Game in Flutter.
Any number of people can work on a single issue,
This issue is open to all.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by rutuja1121** [comment]
What changes do you want in this project?

**Comment by areeba-farooq** [comment]
I would love to contribute to this issue. can you please assign this to me?

**Comment by G1Joshi** [comment]
This Issue is open to all and we want as much quantity PR as our Community can build.
**Happy C0D1NG** 🚀

**Comment by PrajwalGKale** [comment]
## Greetings, @gdsc-mitadt
>**I was looking for a repository to contribute to open source and found this one.**
**Can you assign this to me? I'm familiar with the *Flutter framework* .**
